- hosts: master
  become: yes
  tasks:
    - name: initialize the cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: ric
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copies admin.conf to user's ric config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ric/.kube/config
        remote_src: yes
        owner: ric

    - name: install Pod network
      become: yes
      become_user: ric
      shell: kubectl apply -f https://docs.projectcalico.org/archive/v3.17/manifests/calico.yaml 
      args:
        chdir: $HOME

    - name: install pip3
      apt: name=python3-pip state=present

    - name: install pre-requisites
      pip:
        name:
                #- openshift
                #          - pyyaml
          - kubernetes

    - name: Remove taint node "localhost"
      kubernetes.core.k8s_taint:
        state: absent
        name: localhost
        taints:
        - effect: NoSchedule
          key: "node-role.kubernetes.io/master"
        
    - name: Get the token for joining the worker nodes
      become: yes
      become_user: ric
      shell: kubeadm token create  --print-join-command
      register: kubernetes_join_command

      #    - debug:
      #      msg: "{{ kubernetes_join_command.stdout }}"

    - name: Copy join command to local file.
      become: yes
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777
