- hosts: all
  become: yes
  tasks:
  - name: start the cluster
    shell: kubeadm init --pod-network-cidr=10.244.0.0/16
    args:
      chdir: $HOME
    async: 60
    poll: 60

  - name: create a new directory to hold kube conf
    become: yes
    become_user: ric
    file:
      path: $HOME/.kube
      state: directory
      mode: 0755

  - name: copy configuration file to the newly created dir
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/ric/.kube/config
      remote_src: yes
      owner: ric

  - name: set kubeconfig file permissions
    file:
      path: /home/ric/.kube/config 
      owner: "{{ ansible_effective_user_id }}"
      group: "{{ ansible_effective_group_id }}"

  - name: Remove taint node "localhost"
    kubernetes.core.k8s_taint:
      state: absent
      name: localhost
      taints:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
              


  - name: Apply a calico manifset to init the pod network
    become: yes
    become_user: ric
    shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml 
    args:
      chdir: $HOME
        
      #  - name: Get the join command to be used by the worker
      #    become: yes
      #    become_user: ric
      #    shell: kubeadm token create  --print-join-command
      #    register: ric_join_command

      #  - name: Save the join command to a local file
      #    become: yes
      #    local_action: copy content="{{ ric_join_command.stdout_lines[0] }}" dest="/etc/ric_join_command" mode=0777
