- hosts: "master, worker"
  remote_user: ric
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh

  tasks:

    - name: Install grafana
      yum:
        name: https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana-{{ version }}-1.x86_64.rpm
        state: latest
