- hosts: all
  become: yes
  tasks:
  - name: create the 'ric' user
    user: name=ric append=yes state=present createhome=yes shell=/bin/bash groups=sudo append=yes

  - name: allow 'ric' to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      line: 'ric ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

  - name: create a new directory to hold ssh key
    become: yes
    become_user: ric
    file:
      path: $HOME/.ssh
      state: directory
      mode: 0755

  - name: copy ssh files ds destination
    copy:
      src: id_rsa.pub
      dest: /home/ric/.ssh/id_rsa.pub
      remote_src: false
      owner: ric

  - name: set up authorized keys for the ric user
    authorized_key: user=ric key="{{item}}"
    with_file:
      - /home/ric/.ssh/id_rsa.pub

- hosts: all
  tasks:
  - name: create a new directory to add pub docker key
    become: true
    become_user: root
    file:
      path: /etc/apt/keyrings
      state: directory
      mode: 0755
  - name: Add docker signing key (new GPG method)
    get_url:
      url: https://download.docker.com/linux/ubuntu/gpg
      dest: /etc/apt/keyrings/docker.gpg
      mode: '0644'
      force: true
  - name: Add docker repository
    apt_repository:
      repo: deb [signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu focal stable
      state: present

- hosts: all
  become: yes
  tasks:
  - name: install APT Transport HTTPS
    apt:
      name: apt-transport-https
      state: present

  - name: add Kubernetes apt-key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: add 'kubernetes' APT repository
    become: true
    become_user: root
    apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: 'kubernetes'

  - name: install kubelet
    apt:
      name: kubelet
      state: present
      update_cache: true
      become_user: ric
      become: true

  - name: install kubeadm
    apt:
      name: kubeadm
      state: present
      become_user: ric
      become: true

  - pause: seconds=5
