- hosts: all
  become: yes
  tasks:
  - name: create the 'ric' user
    user: name=ric append=yes state=present createhome=yes shell=/bin/bash groups=sudo append=yes

  - name: allow 'ric' to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      line: 'ric ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

  - name: set up authorized keys for the ric user
    authorized_key: user=ric key="{{item}}"
    with_file:
      - /home/ric/.ssh/id_rsa.pub

- hosts: all
  become: yes
  tasks:
  - name: Add docker signing key (new GPG method)
    get_url:
      url: https://download.docker.com/linux/ubuntu/gpg
      dest: /etc/apt/keyrings/docker.asc
      mode: '0644'
      force: true 
  - name: Add docker repository
    apt_repository:
      repo: deb [signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu jammy stable
      state: present
